
policy: "MLP"

env:
  dataset: "Pakistan"
  flag: "Tuple30K"
  refresh_rate: 0.001

training:
  num_epochs: 5
  batch_size: 256
  lr: 0.002
  gamma: 0.2
  epsilon: 0.1
  epsilon_decay: 0.96

model:
  d_model: 128
  n_layers: 3
  obs_type: ["cpu", "bw", "buffer"]

    