
policy: "TaskFormer"

env:
  dataset: "Pakistan"
  flag: "Tuple30K"
  refresh_rate: 0.001

training:
  num_epochs: 5
  batch_size: 256
  lr: 0.002
  gamma: 0.2
  epsilon: 0.1
  epsilon_decay: 0.96
  beta: 0.5
  beta_decay: 0.96

model:
  d_model: 64
  n_layers: 6
  n_heads: 4
  mlp_ratio: 4
  dropout: 0.1  
  mode: "mixed" # "mixed", node, task

    