
policy: "MLP"
algo: "MLP"

seed: 42

env:
  dataset: "Topo4MEC"
  flag: "25N50E"
  refresh_rate: 0.1

training:
  num_epochs: 5
  batch_size: 1024
  lr: 0.0005
  lr_decay: 0.95
  gamma: 0.
  epsilon: 0.1
  epsilon_decay: 0.6
  reward_scale: 10000
  lambda: [1, 0.1, 0.05]

model:
  d_model: 128
  n_layers: 3
  # obs_type: ["cpu"]
  obs_type: ["cpu", "buffer"]
  # obs_type: ["cpu", "bw", "buffer"]

eval:
  lambda: [1, 0.1, 0.01]
  expected_max_latency: 250
  expected_max_energy: 5