
policy: "TaskFormer-S"
algo: "TaskFormer"

env:
  dataset: "Topo4MEC"
  flag: "25N50E"
  refresh_rate: 0.1

training:
  num_epochs: 20
  batch_size: 256
  lr: 0.01
  gamma: 0.2
  epsilon: 0.1
  epsilon_decay: 0.5
  beta: 0.5
  beta_decay: 0.6

model:
  d_model: 64
  n_layers: 6
  n_heads: 4
  mlp_ratio: 4
  dropout: 0.2  
  mode: "task" # "mixed", node, task

eval:
  lambda: [1, 0.1, 0.01]
  expected_max_latency: 250
  expected_max_energy: 5

    