
policy: "MLP"
algo: "MLP"

env:
  dataset: "Pakistan"
  flag: "Tuple30K"
  refresh_rate: 0.005

training:
  num_epochs: 20
  batch_size: 256
  lr: 0.001
  gamma: 0.2
  epsilon: 0.1
  epsilon_decay: 0.6
  lambda: [10000, 1, 1]

model:
  d_model: 128
  n_layers: 3
  # obs_type: ["cpu"]
  obs_type: ["cpu", "bw", "buffer"]
