
policy: "MLP"
algo: "DQL"

seed: 42

env:
  dataset: "Pakistan"
  flag: "Tuple50K"
  refresh_rate: 0.005

eval:
  lambda: [1.889e-03, 4.394e+00, 2.605e+02]


training:
  num_epochs: 20
  learning_starts: 5000    # random steps before learning begins
  warmup: 0                # LR warmup as ratio of total training steps
  buffer_size: 50000      # max replay buffer size
  batch_size: 512          # samples per update
  target_update_freq: 4000  # >= 1 → hard copy every N grad steps | < 1 → soft update with τ = value
  update_freq: 16          # steps between policy updates
  lr: 5.e-5
  lr_decay: 1
  gamma: 0.99
  # Exploration strategy: "epsilon_greedy" (default), "boltzmann", or "ucb"
  exploration: {'strategy': 'ucb', explore_value: 0.5 }

  reward:
    momentum: 0.999
    norm: "log1p_standard"  # "none", "mean", "ln_mean", "standard", "ln_standard"
    scale: 1
    eps: 1.e-2
    clip: 5.0
    storage_norm: true

  optimizer:
    type: "RMSprop"
    weight_decay: 0

  lambda: [0.80000,0.10000,0.100000]
  early_stop_patience: 20 # Early stopping patience (generations without improvement)
  log_freq: 0      # Steps between logging training metrics

model:
  d_model: 128
  n_layers: 2
  # obs_type: ["cpu"]
  # obs_type: ["bw"]
  obs_type: ["cpu", "bw", "buffer"]
  bias: true
  dropout: 0



