
policy: "T-MLP"
algo: "DQL"

seed: 4

env:
  dataset: "Pakistan"
  flag: "Tuple30K"
  refresh_rate: 0.005

eval:
    lambda: [0.001889, 4.394, 260.5]
    expected_values: [0.2, 4.0, 300.0]

training:
    num_epochs: 20
    learning_starts: 5000
    warmup: 0
    buffer_size: 50000
    batch_size: 256
    target_update_freq: 1000
    update_freq: 8
    lr: 8.e-05
    lr_decay: 1
    gamma: 0.99
    exploration: {'strategy': 'ucb', 'explore_value': 1.0}
    reward: {'momentum': 0.999, 'norm': 'log1p_standard', 'scale': 1, 'eps': 0.01, 'clip': 5.0, 'storage_norm': True}
    optimizer: {'type': 'RMSprop', 'weight_decay': 0}
    lambda: [0.35, 0.35, 0.3]
    early_stop_patience: 20
    log_freq: 0

model:
    d_model: 256
    n_layers: 2
    obs_type: ['cpu', 'bw', 'buffer', 'task']

    bias: True
    dropout: 0

device: auto


