policy: OPO
algo: DQL


env:
  dataset: "Pakistan"
  flag: "Tuple30K"
  refresh_rate: 0.005


seed: 42
eval:
    lambda: [0.001889, 4.394, 260.5]
    expected_values: [0.2, 4.0, 300.0]

training:
    num_epochs: 40
    learning_starts: 5000
    warmup: 0
    buffer_size: 50000
    batch_size: 512
    target_update_freq: 1000
    update_freq: 8
    lr: 0.0002
    lr_decay: 1
    gamma: 0.99
    exploration: {'strategy': 'epsilon_greedy', 'epsilon': 1.0, 'epsilon_min': 0.05, 'epsilon_decay': 0.5}
    reward: {'momentum': 0.999, 'norm': 'log1p_standard', 'scale': 1, 'eps': 0.01}
    optimizer: {'type': 'RMSprop', 'weight_decay': 0}
    lambda: [0.35, 0.35, 0.3]
    early_stop_patience: 20
    log_freq: 0


model:
    d_model: 256
    n_layers: 2
    obs_type: ['cpu', 'bw', 'buffer', 'task']
    bias: True
    dropout: 0
    history_window: 64
    lstm_hidden_dim: 256
    lstm_n_layers: 1
    lstm_lr: 0.0005
    prediction_threshold: 0.1
device: auto