
policy: "NATE"
algo: "DQL"

seed: 0

env:
  dataset: "Synthetic"
  flag: "50N100T150D"
  refresh_rate: 0.005


algo: DQL
eval:
    lambda: [0.001889, 4.394, 260.5]

training:
    num_epochs: 40
    learning_starts: 5000
    warmup: 0.1
    buffer_size: 50000
    batch_size: 512
    target_update_freq: 2000
    update_freq: 8
    lr: 3.0e-06
    lr_decay: 1
    gamma: 0.99
    exploration: {'strategy': 'ucb', 'explore_value': 0.5}
    reward: {'momentum': 0.999, 'norm': 'log1p_standard', 'scale': 1, 'eps': 0.01, 'clip': 5.0, 'storage_norm': True}
    optimizer: {'type': 'RMSprop', 'weight_decay': 0.0}
    lambda: [0.35, 0.35, 0.3]
    early_stop_patience: 20
    log_freq: 0

model:
    d_model: 64
    n_layers: 4
    n_heads: 4
    mlp_ratio: 4
    dropout: 0.0
    obs_type: ['cpu', 'bw', 'buffer']
    qk_norm: True
    embed: regular


