policy: "NOTE"
algo: "TaskFormer"

env:
  dataset: "Synthetic"
  flag: "50N100T150D"
  refresh_rate: 0.005

eval:
  lambda: [1.889e-03, 4.394e+00, 2.605e+02]

training:
    num_epochs: 40
    learning_starts: 5000
    warmup: 0.05
    buffer_size: 50000
    batch_size: 512
    target_update_freq: 1000
    update_freq: 8
    lr: 5.e-05
    lr_decay: 1
    gamma: 0.99
    exploration: {'strategy': 'ucb', 'explore_value': 1.}
    reward: {'momentum': 0.999, 'norm': 'log1p_standard', 'scale': 1, 'eps': 0.01, 'clip': 5.0, 'storage_norm': True}
    optimizer: {'type': 'RMSprop', weight_decay: 0.01}
    lambda: [0.35, 0.35, 0.3]
    early_stop_patience: 30
    log_freq: 0
    clip_grad_norm: 1.0

model:
    d_model: 64
    n_layers: 4
    n_heads: 2
    mlp_ratio: 4
    dropout: 0.1
    mode: node
    obs_type: ['cpu', 'bw', 'buffer']
device: auto
