
policy: "T-NATE"
algo: "DQL"

seed: 2

env:
  dataset: "Synthetic"
  flag: "50N100T150D"
  refresh_rate: 0.005


algo: DQL
eval:
    lambda: [0.001889, 4.394, 260.5]

training:
    num_epochs: 50
    learning_starts: 5000
    warmup: 0.1
    cooldown: 0.0
    buffer_size: 100000
    batch_size: 32
    target_update_freq: 10000
    update_freq: 32
    lr: 1.0e-05
    ref_d_model: 256
    lr_decay: 1
    gamma: 0.99
    # exploration: {'strategy': 'ucb', 'explore_value': 0.5}
    exploration: {'strategy': 'epsilon_greedy', 'explore_value': 0.3, 'explore_min': 0.01, 'explore_decay': 0.7}
    reward: {'momentum': 0.9995, 'norm': 'standard', 'scale': 1, 'eps': 0.1, 'clip': 5.0, 'storage_norm': True, log1p: True}
    optimizer: {'type': 'Adam', 'weight_decay': 0.0}
    lambda: [0.5, 0.4, 0.1]
    early_stop_patience: 30
    log_freq: 0
    clip_grad_norm: 10.0

model:
    d_model: 256
    n_layers: 2
    d_heads: 32
    mlp_ratio: 4
    dropout: 0.0
    obs_type: ['cpu', 'bw', 'buffer', 'task']
    qk_norm: True
    embed: regular
    pre_conditioning: add
    n_prefix: 1
    residual_type: plain
