policy: "NSGA2"

env:
  dataset: "Pakistan"
  flag: "Tuple30K"
  refresh_rate: 0.01

training:
  num_epochs: 30        # Number of generations for NPGA
  pop_size: 30          # Population size for NPGA
  mutation_rate: 0.1    # Mutation rate for Gaussian mutation

model:
  d_model: 128
  n_layers: 3
  # obs_type: ["cpu"]
  obs_type: ["cpu", "bw", "buffer"]
