
policy: "NATD"
algo: "DQL"

env:
  dataset: "Pakistan"
  flag: "Tuple30K"
  refresh_rate: 0.005

eval:
  lambda: [1.889e-03, 4.394e+00, 2.605e+02]

training:
  num_epochs: 30
  learning_starts: 5000    # random steps before learning begins
  warmup: 0.05                # LR warmup as ratio of total training steps
  buffer_size: 50000      # max replay buffer size
  batch_size: 256          # samples per update
  target_update_freq: 1000  # >= 1 → hard copy every N grad steps | < 1 → soft update with τ = value
  update_freq: 8          # steps between policy updates
  lr: 8.e-5
  lr_decay: 1
  gamma: 0.99
  exploration: {'strategy': 'ucb', 'explore_value': 10.0}
  reward: {'momentum': 0.999, 'norm': 'log1p_standard', 'scale': 1, 'eps': 0.01}
  optimizer: {'type': 'RMSprop'}
  lambda: [0.35, 0.35, 0.3]
  early_stop_patience: 20
  log_freq: 0
  # clip_grad_norm: 2.0
    
model:
  d_model: 64
  n_layers: 4
  n_heads: 2
  mlp_ratio: 4
  dropout: 0.1
  mode: task
  obs_type: ['cpu', 'bw', 'buffer', 'task']


    
