
policy: "NATE"
algo: "DQL"

seed: 42

env:
  dataset: "Pakistan"
  flag: "Tuple30K"
  refresh_rate: 0.005

algo: DQL

eval:
    lambda: [0.001889, 4.394, 260.5]

training:
  num_epochs: 30
  learning_starts: 5000    # random steps before learning begins
  warmup: 0.1                # LR warmup as ratio of total training steps
  buffer_size: 50000      # max replay buffer size
  batch_size: 32          # samples per update
  target_update_freq: 10000  # >= 1 → hard copy every N grad steps | < 1 → soft update with τ = value
  update_freq: 16          # steps between policy updates
  lr: 5.0e-5
  ref_d_model: 128
  # ref_n_layers: 2
  lr_decay: 1
  gamma: 0.99

  exploration: {'strategy': 'epsilon_greedy', 'explore_value': 0.3, 'explore_min': 0.02, 'explore_decay': 0.7} 

  reward:
    momentum: 0.9995
    norm: "standard"  # "none", "mean", "ln_mean", "standard", "ln_standard"
    log1p: true
    # scale: 1
    eps: 1.e-1
    clip: 5.0
    storage_norm: true

  optimizer:
    type: "Adam"
    weight_decay: 0

  lambda: [0.5500,0.2500,0.2000]
  early_stop_patience: 20 # Early stopping patience (generations without improvement)
  log_freq: 0      # Steps between logging training metrics

model:
    d_model: 128
    n_layers: 1
    d_heads: 32
    mlp_ratio: 4
    dropout: 0.0
    obs_type: ['cpu', 'bw', 'buffer']
    qk_norm: true
    embed: regular
    residual_type: plain

    
