
policy: "NodeFormer"
algo: "TaskFormer"

env:
  dataset: "Topo4MEC"
  flag: "25N50E"
  refresh_rate: 0.1

training:
  num_epochs: 20
  batch_size: 256
  lr: 0.01
  gamma: 0.2
  epsilon: 0.1
  epsilon_decay: 0.5
  lambda: [1, 0.01, 0.001]

model:
  d_model: 64
  n_layers: 6
  n_heads: 4
  mlp_ratio: 4
  dropout: 0.2  
  mode: "node" # "mixed", node, task

    