policy: NSGA2
algo: NSGA2
seed: 1
env:
    dataset: Synthetic
    flag: 50N100T150D
    refresh_rate: 0.005
eval:
    lambda: [0.001889, 4.394, 260.5]
training:
    num_epochs: 800
    pop_size: 190
    mutation_mode: self_adaptive
    mutation_sigma_scope: "individual"   # or "layer"
    mutation_sigma: 0.05
    mutation_tau: 0.1
    early_stop_patience: 200
    min_scores: [0.50, 32.0, 450.0]
    keep_checkpoints: 1
    save_pareto_only: True
model:
    d_model: 64
    n_layers: 2
    obs_type: ['cpu', 'bw', 'buffer']
    activation: relu
device: auto
