policy: "NSGA2"
algo: "NSGA2" 

seed: 42

env:
  dataset: "Pakistan"
  flag: "Tuple30K"
  refresh_rate: 0.005

eval:
  lambda: [5.294, 0.2276, 0.002952]
  expected_max_latency: 4
  expected_max_energy: 300


training:
  num_epochs: 200        # Number of generations for NPGA
  pop_size: 50          # Population size for NPGA
  mutation_rate: 0.1    # Mutation rate for Gaussian mutation

model:
  d_model: 64
  n_layers: 2
  # obs_type: ["cpu"]
  obs_type: ["cpu", "bw", "buffer"]
