policy: "NSGA2"
algo: "NSGA2" 

seed: 42

env:
  dataset: "Pakistan"
  flag: "Tuple30K"
  refresh_rate: 0.005

eval:
  lambda: [5.2941176470586, 0.22760484532528744, 0.0038384767437279347]
  expected_max_latency: 4
  expected_max_energy: 300


training:
  num_epochs: 200         # Number of generations for NPGA
  pop_size: 50            # Population size for NPGA
  mutation_rate: 0.1      # Mutation rate for Gaussian mutation
  early_stop_patience: 40 # Early stopping patience (generations without improvement)

model:
  d_model: 64
  n_layers: 2
  # obs_type: ["cpu"]
  obs_type: ["cpu", "bw", "buffer"]
