
policy: "MLP"
algo: "MLP"

seed: 42

env:
  dataset: "Pakistan"
  flag: "Tuple30K"
  refresh_rate: 0.005

eval:
  lambda: [1, 0.1, 0.01]
  expected_max_latency: 210
  expected_max_energy: 800

training:
  num_epochs: 10
  batch_size: 256
  lr: 0.001
  lr_decay: 0.95
  gamma: 0.2
  epsilon: 0.1
  epsilon_decay: 0.6
  reward_scale: 10000

model:
  d_model: 128
  n_layers: 3
  # obs_type: ["cpu"]
  obs_type: ["cpu", "buffer"]
  # obs_type: ["cpu", "bw", "buffer"]

