
policy: "NodeFormer"
algo: "TaskFormer"

env:
  dataset: "Pakistan"
  flag: "Tuple30K"
  refresh_rate: 0.005

eval:
  lambda: [1, 0.1, 0.01]
  expected_max_latency: 210
  expected_max_energy: 800

training:
  num_epochs: 20
  batch_size: 256
  lr: 0.01
  gamma: 0.2
  epsilon: 0.1
  epsilon_decay: 0.5
  lambda: [1, 0.01, 0.001]

model:
  d_model: 64
  n_layers: 6
  n_heads: 4
  mlp_ratio: 4
  dropout: 0.2  
  mode: "node" # "mixed", node, task

    