
policy: "TaskFormer-S"
algo: "TaskFormer"

env:
  dataset: "Pakistan"
  flag: "Tuple30K"
  refresh_rate: 0.005

eval:
  lambda: [1, 1, 0.1]
  expected_max_latency: 200
  expected_max_energy: 800


Dataset: Pakistan
Flag: Tuple30K

training:
    num_epochs: 10
    batch_size: 256
    lr: 0.005
    lr_decay: 0.95
    gamma: 0.2
    epsilon: 0.2
    epsilon_decay: 0.6
    beta: 0.5
    beta_decay: 0.6
    reward_scale: 1
model:
    d_model: 64
    n_layers: 6
    n_heads: 4
    mlp_ratio: 4
    dropout: 0.2
    mode: task


    