
policy: "NOTE"
algo: "TaskFormer"

env:
  dataset: "Pakistan"
  flag: "Tuple30K"
  refresh_rate: 0.005

eval:
  lambda: [1.889e-03, 4.394e+00, 2.605e+02]
  expected_max_latency: 4
  expected_max_energy: 300

training:
  num_epochs: 40
  learning_starts: 5000    # random steps before learning begins
  warmup: 0                # LR warmup as ratio of total training steps
  buffer_size: 50000      # max replay buffer size
  batch_size: 512          # samples per update
  target_update_freq: 1024 # steps between target network syncs
  update_freq: 8          # steps between policy updates
  lr: 2.e-4
  lr_decay: 1
  gamma: 0.99
  epsilon: 1
  epsilon_decay: 0.4
  lambda: [0.35, 0.35, 0.3]
  early_stop_patience: 25 # Early stopping patience (generations without improvement)
  clip_grad_norm: 1.0          # Max norm for gradient clipping
  log_freq: 0

model:
  d_model: 64
  n_layers: 2
  n_heads: 4
  mlp_ratio: 4
  dropout: 0.1
  mode: node
  obs_type: ["cpu", "bw", "buffer"]


    
