
policy: "CT-NATE"
algo: "DQL"

seed: 0

env:
  dataset: "Pakistan"
  flag: "Tuple100K"
  refresh_rate: 0.005


algo: DQL
eval:
    lambda: [0.001889, 4.394, 260.5]

training:
  num_epochs: 20
  learning_starts: 5000
  warmup: 0.1
  cooldown: 0.2
  buffer_size: 20000
  batch_size: 32
  target_update_freq: 10000
  update_freq: 8
  lr: 5.0e-5
  ref_d_model: 128
  gamma: 0.99
  exploration: {'strategy': 'ucb', 'explore_value': 1.0}
  double_dqn: true

  reward:
    momentum: 0.9995
    norm: "standard"
    scale: 1
    eps: 1.e-1
    clip: 5.0
    storage_norm: true

  optimizer:
    type: "Adam"
    weight_decay: 0

  lambda: [0.3, 0.400, 0.300]
  early_stop_patience: 20
  log_freq: 0
  max_grad_norm: 10.0

model:
    d_model: 256
    n_layers: 1
    d_heads: 64
    mlp_ratio: 4
    dropout: 0.0
    obs_type: ['cpu', 'bw', 'buffer', 'task']
    qk_norm: True
    embed: regular
    softplus_attn: 5.0
