policy: "MLP"
algo: "DQL"

seed: 42

env:
  dataset: "Pakistan"
  flag: "Tuple100K"
  refresh_rate: 0.005

eval:
  lambda: [1.889e-03, 4.394e+00, 2.605e+02]
  expected_values: [0.2, 4.0, 300.0]


training:
  num_epochs: 40
  learning_starts: 5000    # random steps before learning begins
  warmup: 0                # LR warmup as ratio of total training steps
  buffer_size: 50000      # max replay buffer size
  batch_size: 128          # samples per update
  target_update_freq: 5000  # >= 1 → hard copy every N grad steps | < 1 → soft update with τ = value
  update_freq: 1          # steps between policy updates
  lr: 2.0e-4
  lr_decay: 1
  gamma: 0.95
  # Exploration strategy: "epsilon_greedy" (default), "boltzmann", or "ucb"
  exploration: {'strategy': 'ucb', explore_value: 2.0 }

  reward:
    momentum: 0.9995
    norm: "standard"  # "none", "mean", "ln_mean", "standard", "ln_standard"
    log1p: true
    # scale: 1
    eps: 1.e-1
    clip: 5.0
    storage_norm: true

  optimizer:
    type: "Adam"
    weight_decay: 0

  lambda: [0.200, 0.5, 0.300]
  early_stop_patience: 20 # Early stopping patience (generations without improvement)
  log_freq: 0      # Steps between logging training metrics

model:
  d_model: 512
  n_layers: 2
  # obs_type: ["cpu"]
  # obs_type: ["cpu", "buffer"]
  obs_type: ["cpu", "bw", "buffer"]
  bias: true
  dropout: 0

