
policy: "T-NATE"
algo: "DQL"

seed: 0

env:
  dataset: "Pakistan"
  flag: "Tuple100K"
  refresh_rate: 0.005


algo: DQL
eval:
    lambda: [0.001889, 4.394, 260.5]

training:
  num_epochs: 20
  learning_starts: 5000    # random steps before learning begins
  warmup: 0.1               # LR warmup as ratio of total training steps
  cooldown: 0.2               # LR cooldown as ratio of total training steps
  buffer_size: 100000      # max replay buffer size
  batch_size: 256          # samples per update
  target_update_freq: 10000  # >= 1 → hard copy every N grad steps | < 1 → soft update with τ = value
  update_freq: 8          # steps between policy updates
  lr: 5.0e-5
  ref_d_model: 128
  # ref_n_layers: 2
  gamma: 0.99
  # Exploration strategy: "epsilon_greedy" (default), "boltzmann", or "ucb"
  exploration: {'strategy': 'ucb', explore_value: 1.0 }
  double_dqn: true
  # per: 
  #   enabled: true
  #   alpha: 0.5
  #   beta_start: 0.5
  #   beta_end: 1.0
  #   eps: 1.e-5
  
  reward:
    momentum: 0.9995
    norm: "standard"  # "none", "mean"
    scale: 1
    eps: 1.e-1
    clip: 5.0
    storage_norm: true

  optimizer:
    type: "Adam"
    weight_decay: 0

  lambda: [0.3, 0.400, 0.300]
  early_stop_patience: 20 # Early stopping patience (generations without improvement)
  log_freq: 0      # Steps between logging training metrics
  max_grad_norm: 10.0

model:
    d_model: 256
    n_layers: 1
    d_heads: 64
    mlp_ratio: 4
    dropout: 0.0
    obs_type: ['cpu', 'bw', 'buffer', 'task']
    qk_norm: True
    embed: regular  
    pre_conditioning: add  # 'add' or 'concat'
    n_prefix: 2


